spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testsqldb?characterEncoding=utf-8&useSSL=false
    username: root
    password: CHENchen2011
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081


